language: elixir

otp_release:
  - 17.5
  - 18.3

elixir:
  - 1.0.5
  - 1.1.1
  - 1.2.6

matrix:
  exclude:
    - otp_release: 17.5
      elixir: 1.2.6
    - otp_release: 18.3
      elixir: 1.0.5

sudo: false # to use faster container based build environment
